### ISSUE TITLE
Generate `ActiveRecord::Migration[VERSION]`

### ISSUE THREAD

**Issue by mxmCherry** [bsm/grape-app#7]
https://github.com/bsm/grape-app/blob/5101278d6fd27d98d95e9f7a5237e6cc8f4e4bfd/lib/grape/app/tasks/databases.rake#L36

Any concerns to focus on AR 5.2?

**Comment by dim** [comment]
you can just use `[ActiveRecord::VERSION::MAJOR, ActiveRecord::VERSION::MINOR].join('.')`

**Comment by mxmCherry** [comment]
So you'll accept such PR?

**Comment by dim** [comment]
any time
